import pandas as pd, numpy as np, os, glob, re
BASE = r"C:\Users\JC\Desktop\Tesis"

# Load the 2026 samples (fresh run with correct ERA5)
s26 = pd.read_csv(os.path.join(BASE, "datasets", "samples_2026_s2_chl.csv"))
s26["fecha"] = pd.to_datetime(s26["fecha"])
s26 = s26[s26["temp_air_2m"].notna()].copy()  # only valid ERA5
s26["region"] = s26["region"].fillna("")
s26["archivo_s2"] = s26["archivo_s2"].fillna("")
print(f"2026 samples (valid ERA5): {len(s26)}, HAB={s26['es_floracion'].sum()}")

# Collect all original 2023-2025 data from the matching pipeline
# The original Florida data: WQP + MODIS matched in earlier pipeline
# We need only samples with real (not estimated) chlorophyll
# These were generated by the matching pipeline before any 2026 work

# Load individual region CSVs if they exist
old_samples = []
csv_dir = os.path.join(BASE, "datasets", "florida")
for f in glob.glob(os.path.join(csv_dir, "*matched*.csv")):
    try:
        df = pd.read_csv(f, low_memory=False)
        if "fecha" in df.columns and "clorofila_ugl" in df.columns:
            df["fecha"] = pd.to_datetime(df["fecha"], errors="coerce")
            df = df[df["fecha"].dt.year >= 2023]
            if len(df) > 0:
                old_samples.append(df)
                print(f"  {os.path.basename(f)}: {len(df)} samples")
    except:
        pass

for f in glob.glob(os.path.join(BASE, "datasets", "honduras", "*matched*.csv")):
    try:
        df = pd.read_csv(f, low_memory=False)
        if "fecha" in df.columns and "clorofila_ugl" in df.columns:
            df["fecha"] = pd.to_datetime(df["fecha"], errors="coerce")
            df = df[df["fecha"].dt.year >= 2023]
            if len(df) > 0:
                old_samples.append(df)
                print(f"  {os.path.basename(f)}: {len(df)} samples")
    except:
        pass

# Also check for the full dataset
full_ds = pd.read_csv(os.path.join(BASE, "datasets", "dataset_entrenamiento_completo_2023_2026.csv"))
full_ds["fecha"] = pd.to_datetime(full_ds["fecha"])
# Keep only original data with real ERA5 - before any 2026 pipeline contamination
# These have 'origen' from the original matching pipeline
original = full_ds[(full_ds["fecha"].dt.year >= 2023) & 
                   (full_ds["fecha"].dt.year <= 2025) &
                   full_ds["temp_air_2m"].notna()].copy()
print(f"\nOriginal from full CSV (2023-2025): {len(original)}")

# Filter to only the original sources (exclude any that came from the 2026 pipeline)
# The 2026 pipeline samples are in 's26', everything else comes from matching pipeline
original = original[~original["fecha"].dt.year.isin([2026])].copy()

# Standardize columns
cols_target = ["fecha","origen","B2","B3","B4","B5","B8","clorofila_ugl","es_floracion",
               "lat","lon","temp_air_2m","solar_radiation","precipitation","wind_speed_10m",
               "wind_u_10m","wind_v_10m","surface_pressure"]

if "lat" not in original.columns:
    original["lat"] = original.get("latitud", np.nan)
    original["lon"] = original.get("longitud", np.nan)
if "lat" not in s26.columns and "latitud" in s26.columns:
    s26["lat"] = s26["latitud"]
    s26["lon"] = s26["longitud"]

original_out = original[[c for c in cols_target if c in original.columns]].copy()
s26_out = s26[[c for c in cols_target if c in s26.columns]].copy()

full = pd.concat([original_out, s26_out], ignore_index=True)
full = full.sort_values("fecha").reset_index(drop=True)
print(f"\nFinal 2023-2026: {len(full)} samples, HAB={full['es_floracion'].sum()} ({full['es_floracion'].mean()*100:.1f}%)")
print(f"Years: {sorted(full['fecha'].dt.year.unique())}")
print(f"Origen: {full['origen'].value_counts().to_dict()}")

# Save
full.to_csv(os.path.join(BASE, "datasets", "dataset_entrenamiento_completo_2023_2026.csv"), index=False)
print("Saved clean dataset")
